### ISSUE TITLE
Weird regions hoping on zoom level 5

### ISSUE THREAD

**Issue by xkomczax** [openmaptiles/klokantech-basic-gl-style#21]
On zoom level 5, detailed region borders appears in many countries (e.g. Czech Republic, France, ...). 
On zoom level 6, they disappear and instead superior regions boundaries appear (which are less detailed). 
An example is visible on [this map](https://www.maptiler.com/maps/#basic//vector/5.98/5.055/47.927) if you zoom in - instead of more details, you see less.

**Comment by pathmapper** [comment]
These boundaries are not included in the tiles on zoom level 6,7,8 and therefore could not be displayed.

Example:
https://www.openstreetmap.org/relation/7394

OSM `admin_level` = 6
NE 4.0 `scalerank` = 5 (changed to 3 with NE 4.1)
NE 4.0 `minzoom` = 8

On zoom level 5, these borders are included in the tiles from natural earth:
https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.sql#L62-L64

On zoom level 6,7,8 these are missing because only `admin_level` <= 4 are considered:
https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.sql#L71-L90

Starting with zoom level = 9, these boundaries are included again in the tiles:
https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/boundary.sql#L92-L97

**Comment by eva-j** [comment]
Solved in https://github.com/openmaptiles/openmaptiles/pull/613, discussion about zoom levels 7 and 8 in https://github.com/openmaptiles/openmaptiles/pull/617.
